### ISSUE TITLE
Add gamepad options

### ISSUE THREAD

**Issue by BerntA** [marsinstituteSC/MissionControl#16]
Allow user to select which gamepad ID to use? Use pygame to generate a list of available IDs / controllers? Test on control station using the bluetooth controller + a usb based one?
Also allow the user to re-connect the gamepad if for example you plugged in/connected the gamepad after starting the app.

**Comment by Segath** [comment]
Haven't been able to test for multiple gamepads, but managed to unplug and plug the gamepad back in.
