### ISSUE TITLE
Advanced: Display a 3d or 2d model of the rover

### ISSUE THREAD

**Issue by Segath** [marsinstituteSC/MissionControl#18]
<h2>This will probably be quite stressfull for the pc and only an idea I remembered Rein mentioned</h2>

The idea here is to create a model of the rover, which is created beforehand, and allow the user to hover over each part and get information about it. Most likely warnings, change the affected part to red so it is easier to see the faulty part.

Could be made simpler with a widget with multiple labels with a picture of the rover part, approximately to the real position and when the logger gets a warning, change the label to red.

**Comment by BerntA** [comment]
This would be pretty cool!

**Comment by Segath** [comment]
Dropped, for new we will use a simple status to reduce the load on the control station.
