### ISSUE TITLE
Dummy sensor data server

### ISSUE THREAD

**Issue by Segath** [marsinstituteSC/MissionControl#2]
Create a dummy udp server that serves dummy data to store in a database (postgresql). Can also update the main windows counters (speed, temp...etc) with the new read value.

**Comment by BerntA** [comment]
We could use rover_server.py, it already acts as the dummy rover udp server, in udp_conn.py we also already check incoming packets, we just need to sort out which ones we care about, if we get a packet we care about, write to DB + some graph maybe.
