### ISSUE TITLE
A way to distribute the incoming json messages onto the main window widgets

### ISSUE THREAD

**Issue by Segath** [marsinstituteSC/MissionControl#31]
Haven't looked too much if there is one, just close this if it exists.

**Comment by BerntA** [comment]
This should be covered already yeah, in the main window, subscribes to an event @ udp conn:
`
    @pyqtSlot('PyQt_PyObject')
    def receivedDataFromRover(self, data):
        # TODO Add more stuff here...
        if 'speed' in data:
            self.setSpeedometerValue(data['speed'])
            self.log.logData("Now running at {} m/s.".format(data['speed']), 0)
`

once we know what the incoming data looks like we can add more stuff to that method.. :+1:
